language: node_js
node_js:
- '6'
services:
- mongodb
- docker
cache:
- yarn
before_install:
- cd src
- npm install -g yarn
install:
- yarn
before_script:
- sleep 15
script:
- npm run test-cov-lcov
after_success:
- cat ./lcov.info | ./node_modules/.bin/coveralls
- cd ..
- docker build -t $TRAVIS_REPO_SLUG:latest .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $TRAVIS_REPO_SLUG:latest;
notifications:
  slack:
    secure: VGpqblryOHSKlbSTI+OuzgZE11n1CaqEcT6Y+mWwr3Qex94JZeVCmhrUBtg1ktV7lDbGYKdxFlZWiNWBPIUDbzneeJtnyyRhL4FV7z/C3AdM1/8IoeoIz2hIPIVU76rwSnOzSkFyoISQ1HOf7v3Fg6jcb1R7IM9xQTk9O5wWsVv9H9z3oUn1eeVaUe76rpN4327lb58cybknKINNznjcuu9QEAtW5wYdiacAN5V/WW3AJG15TgvX4s2NbDpNA3kD7xTzrt1iz82LelMlzd9JISddXdEROBa8nPi+oqdYWRqQpgpSrtxAgRyfnU5/n4ADYduzR9wnK/IqSoOQsjgRvlejeS9tP2+Hh+OHdHzSU4wvhJaJD+ESBmVAK2CaKFt1IWjP2edBjlWKeVMcPaEfMD53H6Hoenmh/CwEQjVOKalYB6cwb200Z3gA3zsGu/frcrfB55FqGmTd0Ks9QfpOSotCook4twp0h9/5ze64NboyUHXEp46HYa2tOtg3L27N6GntuzLiC5G0WmOEie8wsggkUb+boZOc2u6fLt4yZ754V+w83S3TUbZTFft7SBiMojRFAinnmtKTmBuTMrTgrJUkm3LPuRDGXfFi8BdJD6iWgOzTQjGDhYDCOqkdZ2Z8cEGEq8KzQ8zg0uXEoOiZqu9rmwJ61KiYRLMLbRNqmTg=
